-- Checklists — Phase 1 schema (Supabase / Postgres).
-- A manager assigns recurring or one-off tasks to a person; the person checks
-- them off per day. AI-compatible: clean tables the assistant can read (Phase 2)
-- and later complete via confirm-gated writes (Phase 3). See docs/FUTURE_FEATURES.md.
--
-- RLS mirrors the rest of the app: public SELECT (the whole site is behind the
-- PIN gate); writes gated by is_admin(store) or "your own staff row".

-- ── tables ────────────────────────────────────────────────────────────────
create table if not exists public.checklist_items (
  id                bigint generated by default as identity primary key,
  title             text not null,
  details           text,
  store             text,                                  -- nullable = any store (context)
  assignee_staff_id bigint references public.staff(id) on delete cascade,
  recurrence        text not null default 'once',          -- 'once' | 'daily' | 'weekly'
  weekdays          int[] not null default '{}',           -- weekly: 0=Sun .. 6=Sat
  due_date          date,                                  -- once
  priority          text not null default 'normal',        -- 'low' | 'normal' | 'high'
  category          text,
  est_minutes       int,
  active            boolean not null default true,
  created_by        bigint references public.staff(id),
  created_at        timestamptz not null default now()
);

create table if not exists public.checklist_completions (
  id        bigint generated by default as identity primary key,
  item_id   bigint not null references public.checklist_items(id) on delete cascade,
  staff_id  bigint not null references public.staff(id) on delete cascade,
  done_date date   not null,
  done_at   timestamptz not null default now(),
  done_by   bigint references public.staff(id),
  note      text,
  unique(item_id, done_date)
);

create index if not exists ix_cl_items_assignee on public.checklist_items(assignee_staff_id) where active;
create index if not exists ix_cl_comp_item_date on public.checklist_completions(item_id, done_date);

-- ── RLS ───────────────────────────────────────────────────────────────────
alter table public.checklist_items       enable row level security;
alter table public.checklist_completions enable row level security;

-- items: anyone signed into the site can read; admins (for the task's store) manage
drop policy if exists cl_items_read on public.checklist_items;
create policy cl_items_read on public.checklist_items for select to public using (true);
drop policy if exists cl_items_ins on public.checklist_items;
create policy cl_items_ins on public.checklist_items for insert to authenticated with check (is_admin(store));
drop policy if exists cl_items_upd on public.checklist_items;
create policy cl_items_upd on public.checklist_items for update to authenticated using (is_admin(store)) with check (is_admin(store));
drop policy if exists cl_items_del on public.checklist_items;
create policy cl_items_del on public.checklist_items for delete to authenticated using (is_admin(store));

-- completions: public read; you complete your own rows, admins can override
drop policy if exists cl_comp_read on public.checklist_completions;
create policy cl_comp_read on public.checklist_completions for select to public using (true);
drop policy if exists cl_comp_ins on public.checklist_completions;
create policy cl_comp_ins on public.checklist_completions for insert to authenticated
  with check (is_admin() or staff_id = (select s.id from staff s where s.auth_uid = auth.uid()));
drop policy if exists cl_comp_upd on public.checklist_completions;
create policy cl_comp_upd on public.checklist_completions for update to authenticated
  using (is_admin() or staff_id = (select s.id from staff s where s.auth_uid = auth.uid()))
  with check (is_admin() or staff_id = (select s.id from staff s where s.auth_uid = auth.uid()));
drop policy if exists cl_comp_del on public.checklist_completions;
create policy cl_comp_del on public.checklist_completions for delete to authenticated
  using (is_admin() or staff_id = (select s.id from staff s where s.auth_uid = auth.uid()));

-- ── permissions (managed in Settings like every other tool) ────────────────
insert into public.permissions (key,label,category,page,sort,is_access)
select v.key,v.label,v.category,v.page,v.sort,v.is_access from (values
  ('checklist.view','Access My Checklist','My Checklist','My Checklist',43,true),
  ('checklist.manage','Access Checklist Admin','Checklist','Checklist Admin',66,true)
) as v(key,label,category,page,sort,is_access)
where not exists (select 1 from public.permissions p where p.key = v.key);

-- grant: My Checklist -> everyone ; Checklist Admin -> owner + admin
insert into public.role_permissions (role_id, permission_id)
  select r.id, p.id from roles r, permissions p
  where p.key = 'checklist.view' and r.key in ('owner','admin','team_member')
on conflict do nothing;
insert into public.role_permissions (role_id, permission_id)
  select r.id, p.id from roles r, permissions p
  where p.key = 'checklist.manage' and r.key in ('owner','admin')
on conflict do nothing;
