-- Groundwork for hardening square-pay. PURELY ADDITIVE: nothing read either of
-- these until the edge function deploy that uses them (square-pay v49).
--
-- 1. A permission for taking a payment. square-pay authorized with
--    `if (!takenBy) return 401` -- ANY signed-in person, `candidate` included,
--    could call keyed_charge. There was no payments permission in the catalog
--    to check against, so create one. Granted to owner/admin/team_member --
--    exactly who can take a payment today, so no real user loses access; it
--    only excludes candidate and gives the owner a switch in Settings.
insert into permissions (key, label, category, description, sort, page, is_access) values
  ('payments.take', 'Take a payment (Square terminal)', 'Sales & Pricing',
   'Charge a card through the Square virtual terminal, create a payment link, or push a charge to a store terminal.',
   50, null, false)
on conflict (key) do nothing;

insert into role_permissions (role_id, permission_id)
select r.id, p.id from roles r, permissions p
where p.key = 'payments.take' and r.key in ('team_member','admin','owner')
on conflict do nothing;

-- 2. A stable per-attempt id so a double tap cannot double charge. Every charge
--    path built its Square idempotency key from the row it had just inserted --
--    a NEW row per attempt, therefore a NEW key per attempt, which is exactly
--    what an idempotency key exists to prevent. client_op_id is generated by
--    the browser once per user intent and reused across retries, so the second
--    tap collides here instead of reaching Square. Partial unique index so
--    existing and server-initiated rows can leave it null.
alter table public.square_payments
  add column if not exists client_op_id text;

create unique index if not exists square_payments_client_op_id_key
  on public.square_payments (client_op_id)
  where client_op_id is not null;

comment on column public.square_payments.client_op_id is
  'Browser-generated UUID, stable across retries of one payment attempt. Feeds the Square idempotency key and is uniquely indexed so a double tap collides here rather than charging twice.';
